#! /usr/bin/env python

from time import strftime, time
import subprocess

img_version = strftime("%Y-%m-%d")
edition = "Gnome-uboot"
arch = "aarch64"
img_name = f"ArchLinux-ARM-FydeTab-Duo-{edition}-{img_version}"
install_dir = "arch"
fs = "ext4"
img_type = "image"
img_backend = "loop"
has_uefi = True
use_gpt = True

cmdline = "console=ttyFIQ0,1500000n8 console=tty1 console=both loglevel=7 rw panic=10 init=/sbin/init rootflags=subvol=@ rootfstype=btrfs"
grubcmdl = "console=ttyFIQ0,1500000n8 console=tty1 console=both rw init=/sbin/init"
grubdtb = "dtbs/rockchip/rk3588s-fydetab-duo.dtb"

partition_table = lambda img_size, fs: {
    "FW": ["64s", "65535s", "32M", "NONE"],
    "ROOTFS": ["65536s", "100%", str(int(img_size / 1000) - 32) + "M", fs],
}

partition_prefix = lambda config_dir, disk: [
    ["dd", "if=" + config_dir + "/uboot/idblock.bin", "of=" + disk, "bs=512", "seek=64", "conv=notrunc,fdatasync"],
    ["dd", "if=" + config_dir + "/uboot/uboot.img", "of=" + disk, "bs=512", "seek=16384", "conv=notrunc,fdatasync"],
    ["dd", "if=" + config_dir + "/uboot/resource.img", "of=" + disk, "bs=512", "seek=24580", "conv=notrunc,fdatasync"],
    ["partprobe", disk],
    ["sgdisk", "-e", disk],
    ["partprobe", disk],
    ['sleep', '1'],
    ['lsblk'],
]

partition_suffix = lambda config_dir, disk: [
    ["mkfs.fat", "-v", "-F12", "-n", "BOOT", disk + "p2"],
]

perms = {
    "/etc/": ["0", "0", "755"],
    "/usr/bin/resizefs": ["0", "0", "755"],
    "/usr/bin/zswap-arm-ctrl": ["0", "0", "755"],
    "/usr/bin/pacman-init": ["0", "0", "755"],
    "/usr/bin/oemcleanup": ["0", "0", "755"],
    "/etc/polkit-1/rules.d": ["0", "0", "750"],
    "/etc/sudoers.d": ["0", "0", "750"],
    "/usr/lib": ["0", "0", "755"],
    "/usr/bin": ["0", "0", "755"],
    "/usr": ["0", "0", "755"],
    "/usr/lib/systemd": ["0", "0", "755"],
    "/home/arch/": ["1001", "1001", "750"],
    "/home": ["0", "0", "755"],
}

def main() -> None:
    copyfiles(cfg["config_dir"] + "/rootfs", cfg["install_dir"])
    fixperms()
    pacstrap_packages()
    remove_machine_id()
    fixperms()
    copy_skel_to_users()
    subprocess.run(["cp", "-f", cfg["config_dir"] + "/uboot/boot.scr.uimg", cfg["install_dir"]+"/boot/"])
    #subprocess.run(["cp", "-f", cfg["config_dir"] + "/uboot/rk3588s-fydetab-duo.dtb", cfg["install_dir"]+"/boot/dtbs/rockchip/"])
    logging.info("Partitioning Fydetab Image")
    rootfs_size = get_size(cfg["install_dir"]) + 1048576 # df size + 1GB
    ldev = next_loop()
    makeimg(rootfs_size, ldev)
    partition(ldev, rootfs_size)
    copyfiles(cfg["install_dir"], cfg["mnt_dir"], retainperms=True)
    create_fstab(ldev)
    unmount(ldev)
    compressimage(cfg["img_name"])
    cleanup()

if __name__ == "__main__":
    start = time()
    from imageforge.config import Config
    Config(globals())
    from imageforge.common import *
    from imageforge.partitioning import *
    from imageforge.packages import *
    main()
    logging.info("Time taken: " + str((time() - start) / 60) + " minutes")
